version = "3.9.6"
runner.dialect = scala3

maxColumn = 100
align.preset = more
docstrings.style = Asterisk
docstrings.wrap = no

newlines.topLevelStatements = [before, after]
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
