package io.gruggiero.accordant4s.fixtures

// ═══════════════════════════════════════════════════════════════════════════
//  Smithy fixtures for spec: smithy4s-derivation (Step 2 test oracle).
//
//  Provides the `SmithyBankState` (the user state S), typed behaviours for the
//  4 TestBank operations (generated by smithy4s codegen from test-bank.smithy),
//  and a `genState` generator. Used by the oracle to exercise `SmithyOps.forService`
//  and `SpecBuilder`.
//
//  The generated types (`TestBankGen`, `TestBankOperation`, `*Input`, `*Output`)
//  live in `accordant4s.testbank` (src_managed).
// ═══════════════════════════════════════════════════════════════════════════

import accordant4s.testbank.{
  CreateAccountInput,
  CreateAccountOutput,
  DepositInput,
  DepositOutput,
  GetAccountInput,
  GetAccountOutput,
  WithdrawInput,
  WithdrawOutput
}
import cats.syntax.all._
import cats.{Eq, Hash, Show}
import hedgehog.{Gen, Range}
import io.gruggiero.accordant4s.domain.{
  OperationName,
  Outcome,
  ResponseCheck,
  SpecViolation,
  StateOps
}

object SmithyFixtures:

  // ── The user state S: a map of account id → balance (Long, matching smithy) ──

  final case class SmithyBankState(accounts: Map[String, Long]) derives CanEqual

  object SmithyBankState:
    given Eq[SmithyBankState]   = Eq.fromUniversalEquals
    given Hash[SmithyBankState] = Hash.fromUniversalHashCode
    given Show[SmithyBankState] = Show.fromToString

  given StateOps[SmithyBankState] = StateOps.derived

  val empty: SmithyBankState = SmithyBankState(Map.empty)

  // ── Typed behaviours for each TestBank operation ────────────────────────────

  private val createName0   = OperationName("CreateAccount")
  private val depositName0  = OperationName("Deposit")
  private val withdrawName0 = OperationName("Withdraw")
  private val getName0      = OperationName("GetAccount")

  val createBehaviour
      : (CreateAccountInput, SmithyBankState) => Outcome[CreateAccountOutput, SmithyBankState] =
    (req, s) =>
      val check: ResponseCheck[CreateAccountOutput] =
        case res if res.accountId == req.accountId => ().validNel[SpecViolation]
        case _ => SpecViolation.CheckFailed(createName0, "id mismatch").invalidNel
      Outcome.Next(
        check,
        (res: CreateAccountOutput, _) =>
          s.copy(accounts = s.accounts.updated(res.accountId, res.balance))
      )

  val createMock: (CreateAccountInput, SmithyBankState) => Gen[CreateAccountOutput] =
    (req, _) => Gen.constant(CreateAccountOutput(req.accountId, 0L))

  val depositBehaviour: (DepositInput, SmithyBankState) => Outcome[DepositOutput, SmithyBankState] =
    (req, s) =>
      val check: ResponseCheck[DepositOutput] =
        case res if res.accountId == req.accountId => ().validNel[SpecViolation]
        case _ => SpecViolation.CheckFailed(depositName0, "id mismatch").invalidNel
      Outcome.Next(
        check,
        (res: DepositOutput, _) =>
          s.copy(accounts = s.accounts.updated(res.accountId, res.newBalance))
      )

  val depositMock: (DepositInput, SmithyBankState) => Gen[DepositOutput] =
    (req, s) =>
      Gen.constant(
        DepositOutput(
          req.accountId,
          s.accounts.getOrElse(req.accountId, 0L) + req.amount
        )
      )

  val withdrawBehaviour
      : (WithdrawInput, SmithyBankState) => Outcome[WithdrawOutput, SmithyBankState] =
    (req, s) =>
      val check: ResponseCheck[WithdrawOutput] =
        case res if res.accountId == req.accountId => ().validNel[SpecViolation]
        case _ => SpecViolation.CheckFailed(withdrawName0, "id mismatch").invalidNel
      Outcome.Next(
        check,
        (res: WithdrawOutput, _) =>
          s.copy(accounts = s.accounts.updated(res.accountId, res.newBalance))
      )

  val withdrawMock: (WithdrawInput, SmithyBankState) => Gen[WithdrawOutput] =
    (req, s) =>
      Gen.constant(
        WithdrawOutput(
          req.accountId,
          s.accounts.getOrElse(req.accountId, 0L) - req.amount
        )
      )

  val getBehaviour
      : (GetAccountInput, SmithyBankState) => Outcome[GetAccountOutput, SmithyBankState] =
    (req, _) =>
      val check: ResponseCheck[GetAccountOutput] =
        case res if res.accountId == req.accountId => ().validNel[SpecViolation]
        case _ => SpecViolation.CheckFailed(getName0, "id mismatch").invalidNel
      Outcome.Same(check)

  val getMock: (GetAccountInput, SmithyBankState) => Gen[GetAccountOutput] =
    (req, s) =>
      Gen.constant(GetAccountOutput(req.accountId, s.accounts.getOrElse(req.accountId, 0L)))

  // ── The expected operation names (from the smithy4s ShapeId) ────────────────

  val createName: OperationName   = OperationName("CreateAccount")
  val depositName: OperationName  = OperationName("Deposit")
  val withdrawName: OperationName = OperationName("Withdraw")
  val getName: OperationName      = OperationName("GetAccount")

  val allNames: Set[OperationName] = Set(createName, depositName, withdrawName, getName)

  // ── Generator ───────────────────────────────────────────────────────────────

  val genState: Gen[SmithyBankState] =
    for
      ids <- Gen.string(Gen.alpha, Range.linear(0, 3)).list(Range.linear(0, 5))
      balances = ids.map(_ -> 0L).toMap
    yield SmithyBankState(balances)
