addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.4")
addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"         % "0.14.0")
addSbtPlugin("io.stryker-mutator"           % "sbt-stryker4s"        % "0.21.0")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.33")
addSbtPlugin("org.wartremover"              % "sbt-wartremover"      % "3.5.8")
